name: secure_messaging
description: Secure Messaging

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stomp_dart_client: ^0.4.1
  http: ^0.13.1
  sliding_up_panel: ^1.0.2
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  msix: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true

msix_config:
  display_name: Anonymoose Secure Messaging
  publisher_display_name: CodingShadows
  msix_version: 1.0.1.0
  identity_name: 42441CodingShadows.AnonymooseSecureMessaging
  #  certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  #  certificate_password: 1234 (require if using .pfx certificate)
  publisher: CN=6797D520-5CD6-4C65-B059-1C097E49AF4C
  logo_path: C:\Programming\FlutterProjects\secure_messaging\assets\icon.png
  start_menu_icon_path: C:\Programming\FlutterProjects\secure_messaging\assets\icon.png
  tile_icon_path: C:\Programming\FlutterProjects\secure_messaging\assets\icon.png
  #  vs_generated_images_folder_path: C:\<PathToFolder>\Images
  #  icons_background_color: transparent (or some color like: '#ffffff')
  architecture: x64
  capabilities: 'internetClient'