name: secure_messaging
description: Secure Messaging

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stomp_dart_client: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
